# Generated by Django 3.2.6 on 2022-04-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme_operation', models.DecimalField(decimal_places=2, max_digits=100)),
                ('reste_a_paier', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('description', models.CharField(max_length=200)),
                ('date_de_creation', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('validée et payée', 'Validée Et Payée'), ('pas encore', 'Pas Encore')], default='validée et payée', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name="nom de l'activité")),
                ('activity_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cours_particulier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=200)),
                ('prenom_etudiant', models.CharField(max_length=200)),
                ('prix_matiere', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cours_type', models.CharField(choices=[('individuel', 'Individuel'), ('groupe', 'Groupe')], default='individuel', max_length=20, verbose_name='le type de cours')),
                ('date_de_creation', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100, verbose_name='nom du père')),
                ('father_profession', models.CharField(max_length=300, verbose_name='profession du père')),
                ('father_phone', models.CharField(max_length=20, verbose_name='numéro de téléphone du père')),
                ('father_avatar', models.ImageField(upload_to='avatars/')),
                ('mother_name', models.CharField(max_length=100, verbose_name='nom et prénom de la mère')),
                ('mother_profession', models.CharField(max_length=300, verbose_name='profession de la mère')),
                ('mother_phone', models.CharField(max_length=20, verbose_name='numéro de téléphone de la mère')),
                ('authorized_people', models.TextField(verbose_name="personnes autorisées à récupérer  l'élève")),
                ('subscribed_plan', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('6_mois', '6 Mois'), ('annuel', 'Annuel')], default='mensuel', max_length=30, verbose_name="le plan d'abonement")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parant', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=200, verbose_name="nom de l'élève")),
                ('student_name', models.CharField(max_length=200, verbose_name="prenom de l'élève")),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name="date de naissance de l'élève")),
                ('place_of_birth', models.CharField(max_length=200, verbose_name="Lieu de naissance de l'élève")),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('allergic', models.TextField(blank=True, null=True, verbose_name='Allergie à signaler')),
                ('chronical_sickness', models.TextField(blank=True, null=True, verbose_name='maladie chronique à signaler')),
                ('particular_handicap', models.TextField(blank=True, null=True, verbose_name='handicape particulier à signaler')),
                ('student_gender', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name="le sexe de l'élève")),
                ('student_avatar', models.ImageField(upload_to='avatars/', verbose_name='Image principale')),
                ('scolar_inscription_date', models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription scolaire")),
                ('pedagogic_inscription_date', models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription pedagogique")),
                ('scolar_year', models.CharField(default='21/22', max_length=20, verbose_name='année scolaire')),
                ('last_school_attended', models.CharField(blank=True, max_length=400, null=True, verbose_name='dernière école fréquentée')),
                ('activities', models.ManyToManyField(blank=True, null=True, related_name='fils', to='home.Activity')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fils', to='home.parent')),
            ],
        ),
        migrations.CreateModel(
            name='StudyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1ere année', '1ere année'), ('2eme année', '2eme année'), ('3eme année', '3eme année'), ('4eme année', '4eme année'), ('5eme année', '5eme année'), ('6eme année', '6eme année')], default='1ere année', max_length=20, verbose_name="l'année scolaire")),
                ('level', models.CharField(choices=[('prescolaire', 'Prescolaire'), ('preparatoire', 'Preparatoire'), ('primaire', 'Primaire'), ('moyenne', 'Moyenne'), ('lycéenne', 'Lycéenne')], default='prescolaire', max_length=20, verbose_name="niveau d'étude scolaire")),
                ('classe', models.CharField(blank=True, choices=[('classe 1', 'Classe 1'), ('classe 2', 'Classe 2'), ('classe 3', 'Classe 3'), ('classe 4', 'Classe 4'), ('classe 5', 'Classe 5')], max_length=20, null=True, verbose_name='classe scolaire')),
                ('devision', models.CharField(blank=True, choices=[('tronc_commun_science_et_technologie', 'Tronc commun science et technologie'), ('littéraire', 'Littéraire'), ('scientifique', 'Scientifique'), ('mathématique', 'Mathématique'), ('Math technique(mécanique)', 'Math technique(mécanique)'), ('Math technique(électricité)', 'Math technique(électricité)'), ('Math technique(génie civil)', 'Math technique(génie civil)'), ('gestion et économie', 'Gestion et économie'), ('philosophie', 'Philosophie'), ('langue espagnole', 'Langue Espagnole'), ('langue allemande', 'Langue Allemande')], max_length=50, null=True, verbose_name='Division scolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_villa', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='parant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='type_operation',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='prix_matiere',
        ),
        migrations.AddField(
            model_name='facture',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='magazin',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='magazin',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_de_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('validée et payée', 'Validée Et Payée'), ('pas encore', 'Pas Encore')], default='validée et payée', max_length=30),
        ),
        migrations.DeleteModel(
            name='Fils',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Parant',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.AddField(
            model_name='villa',
            name='magazin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villa', to='home.magazin'),
        ),
        migrations.AddField(
            model_name='student',
            name='study_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='home.studylevel'),
        ),
        migrations.AddField(
            model_name='cours_particulier',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='home.matiere', verbose_name='matiere'),
        ),
        migrations.AddField(
            model_name='cours_particulier',
            name='study_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='particular_courses', to='home.studylevel'),
        ),
        migrations.AddField(
            model_name='abonement',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonements_magazin', to='home.magazin'),
        ),
        migrations.AddField(
            model_name='abonement',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonements', to='home.parent'),
        ),
    ]
