# Generated by Django 3.2.6 on 2022-03-02 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220208_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours_particulier',
            name='cours_type',
            field=models.CharField(choices=[('individuel', 'Individuel'), ('groupe', 'Groupe')], default='individuel', max_length=20, verbose_name='le type du cours'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='authorized_people',
            field=models.TextField(verbose_name="personnes autorisées à récupérer  l'élève"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_phone',
            field=models.CharField(max_length=20, verbose_name='numéro de téléphone du mère'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='subscribed_plan',
            field=models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('6_mois', '6 Mois'), ('annuelle', 'Annuelle')], default='mensuelle', max_length=30, verbose_name="le plan d'abonement"),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="date de naissance de l'élève"),
        ),
        migrations.AlterField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(max_length=200, verbose_name="Lieu de naissance de l'élève"),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_firstname',
            field=models.CharField(max_length=200, verbose_name="nom de l'élève"),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name="le sexe de l'élève"),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=200, verbose_name="prenom de l'élève"),
        ),
        migrations.AlterField(
            model_name='studylevel',
            name='devision',
            field=models.CharField(blank=True, choices=[('tronc_commun_science_et_technologie', 'Tronc commun science et technologie'), ('littéraire', 'Littéraire'), ('scientifique', 'Scientifique'), ('mathématique', 'Mathématique'), ('Math technique(mécanique)', 'Math technique(mécanique)'), ('Math technique(électricité)', 'Math technique(électricité)'), ('Math technique(génie civil)', 'Math technique(génie civil)'), ('gestion et économie', 'Gestion et économie'), ('philosophie', 'Philosophie'), ('langue espagnole', 'Langue Espagnole'), ('langue allemande', 'Langue Allemande')], max_length=50, null=True, verbose_name='Division scolaire'),
        ),
        migrations.AlterField(
            model_name='studylevel',
            name='level',
            field=models.CharField(choices=[('prescolaire', 'Prescolaire'), ('preparatoire', 'Preparatoire'), ('primaire', 'Primaire'), ('moyenne', 'Moyenne'), ('lycéenne', 'Lycéenne')], default='prescolaire', max_length=20, verbose_name="niveau d'étude scolaire"),
        ),
    ]
